require:
- rubocop-performance
- rubocop-rspec

AllCops:
  NewCops: enable

RSpec/FilePath:
  SpecSuffixOnly: true
  #Enabled: false
RSpec/SpecFilePathFormat:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing
Layout/ElseAlignment:
  Enabled: false
Layout/EndAlignment:
  Enabled: false
Layout/HashAlignment:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space
Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  SpaceBeforeBlockParameters: false

Style/ClassVars:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ExplicitBlockArgument:
  Enabled: false
Style/FormatString:
  EnforcedStyle: percent
Style/FormatStringToken:
  EnforcedStyle: unannotated
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Style/HashTransformValues:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '[]'
    '%i': '[]'
    '%w': '()'
Style/PerlBackrefs:
  Enabled: false
Style/RegexpLiteral:
  AllowInnerSlashes: true
